# Generated by Django 3.0 on 2020-04-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField()),
                ('no', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=64)),
                ('p1_cards', models.CharField(blank=True, max_length=64, null=True)),
                ('p2_cards', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('chats', models.ManyToManyField(related_name='game_messages', to='bot.Chat')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_message', to='bot.Game')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='user_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='bot.TgUser'),
        ),
    ]
